"""
Configuration & utilities shared across "Song Recommendation System" case study.

References: Bahga & Madisetti, "Big Data Science & Analytics: A Hands-On Approach",
section 11.3 (Box 11.4 - Box 11.7). Code adapted for Python 3 + Spark 3.x.
"""

import csv
import io
import math
import os
import pickle
import shutil

# --------------------------------------------------------------------------
# Dataset Schema
# --------------------------------------------------------------------------
# Column order for CSV generated by Step 1 (cf. Box 11.4).
# First 10 columns match the book, plus two extra for artist ranking (artist_hotttnesss)
# and display (duration).
COLUMNS = [
    "artist_id",          # 0
    "artist_name",        # 1
    "song_id",            # 2
    "song_name",          # 3
    "loudness",           # 4
    "song_hotttnesss",    # 5
    "tempo",              # 6
    "key_confidence",     # 7
    "mode_confidence",    # 8
    "year",               # 9
    "artist_hotttnesss",  # 10
    "duration",           # 11
]
IDX = {name: i for i, name in enumerate(COLUMNS)}

CLUSTER_COL = "cluster"                        # column added after step 3
CLUSTERED_COLUMNS = COLUMNS + [CLUSTER_COL]

# Four features for clustering. The book uses columns 4..7:
# (loudness, song_hotttnesss, tempo, key_confidence).
# However, song_hotttnesss has many NaN values in this subset, so we default to mode_confidence.
# To match the book exactly, simply modify this list.
FEATURE_COLS = ["loudness", "tempo", "key_confidence", "mode_confidence"]

DEFAULT_K = 10          # number of clusters (book uses 10)
DEFAULT_TOP_N = 10      # number of recommended songs


# --------------------------------------------------------------------------
# Reading / Writing CSV
# --------------------------------------------------------------------------
def parse_csv_line(line):
    """Split a CSV line into a list of fields.

    The book uses `line.split(",")`, but since song/artist names may contain commas,
    here we use the csv module (Step 1 wrote CSV with proper quoting).
    """
    try:
        return next(csv.reader(io.StringIO(line)))
    except StopIteration:
        return []


def to_csv_line(fields):
    """Join a list of fields into a CSV line (quote as needed)."""
    buf = io.StringIO()
    csv.writer(buf, lineterminator="").writerow(list(fields))
    return buf.getvalue()


def is_data_row(fields, min_cols=len(COLUMNS)):
    """Skip empty lines, lines with insufficient columns, and the header line."""
    return len(fields) >= min_cols and fields[IDX["artist_id"]] != "artist_id"


def to_float(value, default=float("nan")):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def to_int(value, default=0):
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return default


def is_number(value):
    """True if the value is a valid real number (not NaN, not infinity)."""
    return isinstance(value, float) and not (math.isnan(value) or math.isinf(value))


# --------------------------------------------------------------------------
# Feature Vectors
# --------------------------------------------------------------------------
def feature_vector(fields, feature_cols=FEATURE_COLS):
    """Extract a feature vector for a song from CSV fields."""
    return [to_float(fields[IDX[col]]) for col in feature_cols]


def valid_vector(vector):
    """Discard songs with NaN/inf features (K-Means cannot handle them)."""
    return all(is_number(v) for v in vector)


def standardize(vector, mean, std):
    """Z-score standardization. Features have very different scales
    (loudness ~ -60..0 dB, tempo ~ 0..250 BPM, confidence ~ 0..1) so if not standardized,
    tempo will dominate the entire distance."""
    return [(v - m) / (s if s > 1e-12 else 1.0) for v, m, s in zip(vector, mean, std)]


def column_stats(features_rdd):
    """Return (mean, std, count) of each feature dimension, computed on an RDD."""
    n = features_rdd.count()
    if n == 0:
        raise ValueError("No valid songs to compute statistics.")
    dim = len(features_rdd.first())
    zero = [0.0] * dim

    def add(a, b):
        return [x + y for x, y in zip(a, b)]

    total = features_rdd.reduce(add)
    total_sq = features_rdd.map(lambda v: [x * x for x in v]).reduce(add)
    mean = [s / n for s in total]
    std = [math.sqrt(max(sq / n - m * m, 0.0)) for sq, m in zip(total_sq, mean)]
    return mean, std, n


# --------------------------------------------------------------------------
# Distance & Cluster Assignment
# --------------------------------------------------------------------------
def closest_point(point, centers):
    """Index of the closest cluster center (cf. closestPoint function in Book 11.6)."""
    best_index, closest = 0, float("+inf")
    for i, center in enumerate(centers):
        dist = sum((p - c) ** 2 for p, c in zip(point, center))
        if dist < closest:
            closest, best_index = dist, i
    return best_index


def euclidean_distance(p, q):
    return math.sqrt(sum((a - b) ** 2 for a, b in zip(p, q)))


def book_distance(p, user_point, center, eps=1e-6):
    """Formula in Box 11.7 (book's euclid_dist function).

    The book maps two songs to "relative deviation from cluster center" and combines
    cosine and magnitude difference:
        similarity = sqrt(cosine^2 + (|c| - |d|)^2)
    and sorts increasingly. Note: cosine here is counter-intuitive (two vectors
    with the same direction give cosine = 1 and are considered "farther") - kept for
    comparison with the book, while the default metric in this program is "euclidean".
    """
    def rel(vec):
        return [(v / (c if abs(c) > eps else eps)) - 1.0 for v, c in zip(vec, center)]

    c = rel(user_point)
    d = rel(p)
    dist1 = math.sqrt(sum(x * x for x in c))
    dist2 = math.sqrt(sum(x * x for x in d))
    if dist1 < eps or dist2 < eps:
        return abs(dist1 - dist2)
    cosine = sum(x * y for x, y in zip(c, d)) / dist1 / dist2
    return math.sqrt(cosine * cosine + (dist1 - dist2) ** 2)


def song_distance(p, user_point, center, metric="euclidean"):
    """Distance between a candidate song and the user's input song (smaller is more similar)."""
    if metric == "book":
        return book_distance(p, user_point, center)
    return euclidean_distance(p, user_point)


# --------------------------------------------------------------------------
# Spark & model persistence
# --------------------------------------------------------------------------
def make_spark_context(app_name, master="local[*]"):
    """Create SparkContext that works when called via `python3 script.py` or `spark-submit`."""
    # pyrefly: ignore [missing-import]
    from pyspark import SparkConf, SparkContext

    conf = SparkConf().setAppName(app_name)
    if not conf.contains("spark.master"):
        conf.setMaster(master)
    sc = SparkContext.getOrCreate(conf=conf)
    sc.setLogLevel("WARN")
    # Automatically distribute common.py to all Spark workers
    # This prevents 'ModuleNotFoundError: No module named common' when using python3 directly
    sc.addPyFile(os.path.abspath(__file__))
    return sc


def save_model(path, model):
    """Save cluster centers + standardization parameters (cf. book's cluster_centers.p)."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "wb") as f:
        pickle.dump(model, f)


def load_model(path):
    with open(path, "rb") as f:
        return pickle.load(f)


def prepare_output_dir(path, overwrite):
    """Spark refuses to overwrite an output directory -> handle it explicitly."""
    if os.path.exists(path):
        if not overwrite:
            raise SystemExit(
                "Directory '%s' already exists. Remove it or re-run with --overwrite." % path
            )
        shutil.rmtree(path)
